#!/bin/bash

# Global Variables

# Fuctions

close() {
    # Logs the user out; locks the user's password; disabled autologin; enables banner message; reboots
    USER=$1

    #if the status file doesn't exist, create it.
    STATUS_FILE="/var/tmp/station/status"
    test -f "$STATUS_FILE" || echo "open" >"$STATUS_FILE"

    STATUS=$(cat "$STATUS_FILE")

    if [ $STATUS = "closed" ]; then
        echo "Station already closed"
        return 0
    else

        #If user is logged in, log them out
        if checkUser $USER; then
            loginctl terminate-user $USER
        fi
        usermod -L $USER &&
            sed --in-place=.bak 's/^AutomaticLoginEnable = true/AutomaticLoginEnable = false/g' /etc/gdm3/custom.conf &&
            sed --in-place=.bak 's/^banner-message-enable=false/banner-message-enable=true/g' /etc/gdm3/greeter.dconf-defaults &&
            echo "closed" > $STATUS_FILE
            systemctl reboot
        return 0
    fi
}

open() {
    # Unlocks the users password; enables autologin; disables banner message; reboots
    USER=$1

    usermod -U $USER &&
        sed --in-place=.bak 's/^AutomaticLoginEnable = false/AutomaticLoginEnable = true/g' /etc/gdm3/custom.conf &&
        sed --in-place=.bak 's/^banner-message-enable=true/banner-message-enable=false/g' /etc/gdm3/greeter.dconf-defaults &&
        systemctl reboot
    return 0
}

function checkUser() {

    for u in $(who | awk '{print $1}' | sort | uniq); do
        if [ "$u" == "$1" ]; then
            return 0
        fi
    done
    return 1

}
#Determine which function the user passed in to the command

case "$1" in
"") ;;
close)
    "$@"
    exit
    ;;
open)
    "$@"
    exit
    ;;
*)
    echo "Unknown function: $1"
    exit 2
    ;;
esac
